### PR TITLE
Update encrypt library to support newer, longer Travis CI keys

### LINKED ISSUE #1: Broken
Always says "Message too long for RSA" no matter how long the input is.

### PR DESCRIPTION
**Pull request by slodki**
jsencrypt library version used so far has problems (like issue #1) with longer keys.
Older Travis accounts have [short keys](https://api.travis-ci.org/repos/rkh/travis-encrypt/key), but newer repos have [longer keys](https://api.travis-ci.org/repos/slodki/travis-encrypt/key) generated by Travis. So old library gives error on never Travis repos.

Updating jsencrypt library fixes problem with new keys. [As you can see](https://slodki.github.io/travis-encrypt/public/) encrypted texts with new longer keys are longer too.

### CODE REVIEW

**Comment by slodki** [comment]
#1

**Comment by rkh** [comment]
Great work!

Do you know why it just returns `false` for projects with a short key?

image

**Comment by rkh** [comment]
Hm, maybe it's not the short key, only getting this for sinatra/sinatra.

**Comment by slodki** [comment]
sinatra/sinatra key received from Travis API is invalid for OpenSSL. You can check this with [my tool](/slodki/travis-encrypt-cli).

```
$ curl --silent "https://api.travis-ci.org/repos/sinatra/sinatra/key"
{"key":"-----BEGIN RSA PUBLIC KEY-----\nMIGJAoGBAOu2Fq27AajMWueT8exYtI4DUV6P8rCokPJmBOoN4rkcNnapnZLUzdBF\nOI6mjuK7OARsjTKd9sH44dXmC1ErvXsYkJu2TiD/eLdlYCcjHcqqdce1/g0WjruS\nMG9djGLuE38nywbTeBSW80DPV0bVG6ndZe385KKFp/9tQwuxHnS1AgMBAAE=\n-----END RSA PUBLIC KEY-----\n","fingerprint":"ef:39:56:6e:2a:09:a2:10:2e:b5:39:ac:3d:3e:e1:05"}

$ cat sinatra_key.txt
-----BEGIN RSA PUBLIC KEY-----
MIGJAoGBAOu2Fq27AajMWueT8exYtI4DUV6P8rCokPJmBOoN4rkcNnapnZLUzdBF
OI6mjuK7OARsjTKd9sH44dXmC1ErvXsYkJu2TiD/eLdlYCcjHcqqdce1/g0WjruS
MG9djGLuE38nywbTeBSW80DPV0bVG6ndZe385KKFp/9tQwuxHnS1AgMBAAE=
-----END RSA PUBLIC KEY-----

$ openssl.exe rsautl -encrypt -pubin -inkey sinatra_key.txt
unable to load Public Key

$ openssl version
OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by slodki** [comment]
@sinatra repo error is the same error as travis-ci/travis-ci#913, or IcecaveStudios/archer#4:

```
$ <sinatra_key.txt tee /dev/stderr | openssl rsa -text -pubin
-----BEGIN RSA PUBLIC KEY-----
MIGJAoGBAOu2Fq27AajMWueT8exYtI4DUV6P8rCokPJmBOoN4rkcNnapnZLUzdBF
OI6mjuK7OARsjTKd9sH44dXmC1ErvXsYkJu2TiD/eLdlYCcjHcqqdce1/g0WjruS
MG9djGLuE38nywbTeBSW80DPV0bVG6ndZe385KKFp/9tQwuxHnS1AgMBAAE=
-----END RSA PUBLIC KEY-----

unable to load Public Key
3073070784:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: PUBLIC KEY

$ <sinatra_key.txt sed 's/ RSA / /' | tee /dev/stderr | openssl rsa -text -pubin
-----BEGIN PUBLIC KEY-----
MIGJAoGBAOu2Fq27AajMWueT8exYtI4DUV6P8rCokPJmBOoN4rkcNnapnZLUzdBF
OI6mjuK7OARsjTKd9sH44dXmC1ErvXsYkJu2TiD/eLdlYCcjHcqqdce1/g0WjruS
MG9djGLuE38nywbTeBSW80DPV0bVG6ndZe385KKFp/9tQwuxHnS1AgMBAAE=
-----END PUBLIC KEY-----

unable to load Public Key
3073119936:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1199:
3073119936:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:374:Type=X509_ALGOR
3073119936:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:699:Field=algor, Type=X509_PUBKEY
3073119936:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:pem_oth.c:83:
```

I think it should be fixed by @travis-ci.

**Pull request merged**
